name: Docker Push
on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get Release
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "DOCKER_RELEASE=grantbirki/fastly-to-insights:${RELEASE_VERSION}" >> $GITHUB_ENV
          echo $DOCKER_RELEASE
      -
        name: QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            grantbirki/fastly-to-insights:latest
            ${{ env.DOCKER_RELEASE }}
